/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HitlRouteImport } from './routes/hitl'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SupervisorRouteRouteImport } from './routes/supervisor/route'
import { Route as WarningsRouteImport } from './routes/warnings'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor/index'
import { Route as SupervisorAnomaliesRouteImport } from './routes/supervisor/anomalies'
import { Route as SupervisorAuditRouteImport } from './routes/supervisor/audit'
import { Route as SupervisorCatalogsRouteImport } from './routes/supervisor/catalogs'
import { Route as SupervisorEscalationsRouteImport } from './routes/supervisor/escalations'
import { Route as SupervisorInspectionsRouteImport } from './routes/supervisor/inspections'
import { Route as SupervisorRulesRouteImport } from './routes/supervisor/rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HitlRoute = HitlRouteImport.update({
  id: '/hitl',
  path: '/hitl',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRouteRoute = SupervisorRouteRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const WarningsRoute = WarningsRouteImport.update({
  id: '/warnings',
  path: '/warnings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorAnomaliesRoute = SupervisorAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorAuditRoute = SupervisorAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorCatalogsRoute = SupervisorCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorEscalationsRoute = SupervisorEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorInspectionsRoute = SupervisorInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => SupervisorRouteRoute,
} as any)
const SupervisorRulesRoute = SupervisorRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SupervisorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/supervisor': typeof SupervisorRouteRouteWithChildren
  '/history': typeof HistoryRoute
  '/hitl': typeof HitlRoute
  '/inspection': typeof InspectionRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/warnings': typeof WarningsRoute
  '/supervisor/anomalies': typeof SupervisorAnomaliesRoute
  '/supervisor/audit': typeof SupervisorAuditRoute
  '/supervisor/catalogs': typeof SupervisorCatalogsRoute
  '/supervisor/escalations': typeof SupervisorEscalationsRoute
  '/supervisor/inspections': typeof SupervisorInspectionsRoute
  '/supervisor/rules': typeof SupervisorRulesRoute
  '/supervisor/': typeof SupervisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/hitl': typeof HitlRoute
  '/inspection': typeof InspectionRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/warnings': typeof WarningsRoute
  '/supervisor/anomalies': typeof SupervisorAnomaliesRoute
  '/supervisor/audit': typeof SupervisorAuditRoute
  '/supervisor/catalogs': typeof SupervisorCatalogsRoute
  '/supervisor/escalations': typeof SupervisorEscalationsRoute
  '/supervisor/inspections': typeof SupervisorInspectionsRoute
  '/supervisor/rules': typeof SupervisorRulesRoute
  '/supervisor': typeof SupervisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/supervisor': typeof SupervisorRouteRouteWithChildren
  '/history': typeof HistoryRoute
  '/hitl': typeof HitlRoute
  '/inspection': typeof InspectionRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/warnings': typeof WarningsRoute
  '/supervisor/anomalies': typeof SupervisorAnomaliesRoute
  '/supervisor/audit': typeof SupervisorAuditRoute
  '/supervisor/catalogs': typeof SupervisorCatalogsRoute
  '/supervisor/escalations': typeof SupervisorEscalationsRoute
  '/supervisor/inspections': typeof SupervisorInspectionsRoute
  '/supervisor/rules': typeof SupervisorRulesRoute
  '/supervisor/': typeof SupervisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/supervisor'
    | '/history'
    | '/hitl'
    | '/inspection'
    | '/login'
    | '/reset-password'
    | '/warnings'
    | '/supervisor/anomalies'
    | '/supervisor/audit'
    | '/supervisor/catalogs'
    | '/supervisor/escalations'
    | '/supervisor/inspections'
    | '/supervisor/rules'
    | '/supervisor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/hitl'
    | '/inspection'
    | '/login'
    | '/reset-password'
    | '/warnings'
    | '/supervisor/anomalies'
    | '/supervisor/audit'
    | '/supervisor/catalogs'
    | '/supervisor/escalations'
    | '/supervisor/inspections'
    | '/supervisor/rules'
    | '/supervisor'
  id:
    | '__root__'
    | '/'
    | '/supervisor'
    | '/history'
    | '/hitl'
    | '/inspection'
    | '/login'
    | '/reset-password'
    | '/warnings'
    | '/supervisor/anomalies'
    | '/supervisor/audit'
    | '/supervisor/catalogs'
    | '/supervisor/escalations'
    | '/supervisor/inspections'
    | '/supervisor/rules'
    | '/supervisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupervisorRouteRoute: typeof SupervisorRouteRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  HitlRoute: typeof HitlRoute
  InspectionRoute: typeof InspectionRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WarningsRoute: typeof WarningsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitl': {
      id: '/hitl'
      path: '/hitl'
      fullPath: '/hitl'
      preLoaderRoute: typeof HitlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warnings': {
      id: '/warnings'
      path: '/warnings'
      fullPath: '/warnings'
      preLoaderRoute: typeof WarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/anomalies': {
      id: '/supervisor/anomalies'
      path: '/anomalies'
      fullPath: '/supervisor/anomalies'
      preLoaderRoute: typeof SupervisorAnomaliesRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/audit': {
      id: '/supervisor/audit'
      path: '/audit'
      fullPath: '/supervisor/audit'
      preLoaderRoute: typeof SupervisorAuditRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/catalogs': {
      id: '/supervisor/catalogs'
      path: '/catalogs'
      fullPath: '/supervisor/catalogs'
      preLoaderRoute: typeof SupervisorCatalogsRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/escalations': {
      id: '/supervisor/escalations'
      path: '/escalations'
      fullPath: '/supervisor/escalations'
      preLoaderRoute: typeof SupervisorEscalationsRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/inspections': {
      id: '/supervisor/inspections'
      path: '/inspections'
      fullPath: '/supervisor/inspections'
      preLoaderRoute: typeof SupervisorInspectionsRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
    '/supervisor/rules': {
      id: '/supervisor/rules'
      path: '/rules'
      fullPath: '/supervisor/rules'
      preLoaderRoute: typeof SupervisorRulesRouteImport
      parentRoute: typeof SupervisorRouteRoute
    }
  }
}

interface SupervisorRouteRouteChildren {
  SupervisorAnomaliesRoute: typeof SupervisorAnomaliesRoute
  SupervisorAuditRoute: typeof SupervisorAuditRoute
  SupervisorCatalogsRoute: typeof SupervisorCatalogsRoute
  SupervisorEscalationsRoute: typeof SupervisorEscalationsRoute
  SupervisorInspectionsRoute: typeof SupervisorInspectionsRoute
  SupervisorRulesRoute: typeof SupervisorRulesRoute
  SupervisorIndexRoute: typeof SupervisorIndexRoute
}

const SupervisorRouteRouteChildren: SupervisorRouteRouteChildren = {
  SupervisorAnomaliesRoute: SupervisorAnomaliesRoute,
  SupervisorAuditRoute: SupervisorAuditRoute,
  SupervisorCatalogsRoute: SupervisorCatalogsRoute,
  SupervisorEscalationsRoute: SupervisorEscalationsRoute,
  SupervisorInspectionsRoute: SupervisorInspectionsRoute,
  SupervisorRulesRoute: SupervisorRulesRoute,
  SupervisorIndexRoute: SupervisorIndexRoute,
}

const SupervisorRouteRouteWithChildren = SupervisorRouteRoute._addFileChildren(
  SupervisorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupervisorRouteRoute: SupervisorRouteRouteWithChildren,
  HistoryRoute: HistoryRoute,
  HitlRoute: HitlRoute,
  InspectionRoute: InspectionRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WarningsRoute: WarningsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
